name: refena_inspector_client
description: The client for the inspector of the Refena state management library.
version: 2.1.1
repository: https://codeberg.org/Tienisto/refena/src/branch/main/refena_inspector_client
topics:
  - refena
screenshots:
  - description: The Refena logo.
    path: resources/icon.png

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.0
  refena: ^3.0.0
  web_socket_channel: '>= 2.4.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
